import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity({ name: 'message' })
@Index(['conversationId', 'createdAt'])
export class Message {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string;

  /** Provider message id (idempotency key for inbound webhooks). */
  @Index({ unique: true })
  @Column({ name: 'external_id', type: 'varchar', length: 128, nullable: true })
  externalId!: string | null;

  @Column({
    type: 'varchar',
    length: 10,
  })
  direction!: 'in' | 'out';

  /**
   * Who/what produced this outbound message:
   *   - ai     : generated by the auto-reply AI
   *   - human  : manually sent by an owner/staff member
   *   - system : automated system messages (e.g. "AI takeover")
   * Inbound messages always have author="contact".
   */
  @Column({
    type: 'varchar',
    length: 10,
  })
  author!: 'contact' | 'ai' | 'human' | 'system';

  @Column({
    type: 'varchar',
    length: 20,
    default: 'text',
  })
  type!: 'text' | 'image' | 'audio' | 'video' | 'document' | 'location';

  @Column({ type: 'text', nullable: true })
  body!: string | null;

  /** Provider-specific JSON for media URLs, template params, etc. */
  @Column({ type: 'jsonb', default: () => "'{}'::jsonb" })
  metadata!: Record<string, unknown>;

  @Column({
    type: 'varchar',
    length: 20,
    default: 'sent',
  })
  status!: 'sent' | 'delivered' | 'read' | 'failed';

  @CreateDateColumn({ name: 'created_at' })
  createdAt!: Date;
}
